### ISSUE TITLE
Class smtp-validator does not exist

### ISSUE THREAD

**Issue by x8Haider** [samolabams/smtp-validator#1]
Hi,

I'm using Laravel 5.6 and install the package via composer.
The app is throwing this error--> Class smtp-validator does not exist!

**Comment by samolabams** [comment]
Sorry for the late response. Some changes were made to the files. Kindly uninstall the current one and reinstall the package.

**Comment by x8Haider** [comment]
Hi,

Thanks for the update, but the issue still persist.

 ReflectionException (-1)
Class smtp-validator does not exist
/vendor/laravel/framework/src/Illuminate/Container/Container.php 

 $reflector = new ReflectionClass($concrete);

**Comment by samolabams** [comment]
1. Uninstall the package with `composer remove samolabams/smtp-validator`
2. Clear composer cache with `composer clearcache`
3. Reinstall the package with `composer require samolabams/smtp-validator`
4. Run `composer dump-autoload`

This will solve your issue.

**Comment by x8Haider** [comment]
No idea! I have done all your steps and same issue is still there!!

**Comment by x8Haider** [comment]
I'm using it in my controller file.. i'm adding:
use SmtpValidator;

Hope doing it right !!

**Comment by x8Haider** [comment]
Changing it to:
use Samolabams\SmtpValidator\SmtpValidator;
solve it but got new issue:

Non-static method Samolabams\SmtpValidator\SmtpValidator::newValidation() should not be called statically

**Comment by x8Haider** [comment]
Got that by doing below:

$smtp = new SmtpValidator();
$data = $smtp->newValidation($target, $port)->validate();

**Comment by samolabams** [comment]
Now finally resolved. it was an issue with the tagged branch (wasn't updated with the changes i made). Uninstall and reinstall again. and follow the readme instructions

**Comment by samolabams** [comment]
Hope its now working as expected
